name: perthesmetrics
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch=2.5.1
  - torchvision
  - pytorch-cuda=12.4
  - pip:
      - -r requirements.txt
